# jekyll config
safe:      true
lsi:       false
pygments:  true
permalink: /news/:title/
markdown:  redcarpet
redcarpet:
  extensions: ["tables"]
gems:
  - jekyll-redirect-from

# custom config
cachebust: 1